name: fl_chart
description: A powerful Flutter chart library, currently supporting Line Chart, Bar Chart and Pie Chart.
version: 0.13.0
homepage: https://github.com/imaNNeoFighT/fl_chart

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.0
  path_drawing: ^0.5.0-nullsafety.0


dev_dependencies:
  flutter_test:
    sdk: flutter
